### ISSUE TITLE
New cap

### ISSUE THREAD

**Issue by MateusGuedess** [yaradigitallabs/eslint-config-yara#1]
I suggest to change "new-cap": "error" to "new-cap": "warn" because the function Router of express is getting problem.

@talesbaz 
@kryptogeist 
@nathpaiva 
@vitor-tadashi 
@VitorVRS

**Comment by talesbaz** [comment]
@MateusGuedess, can you give more details of your case, please?!

**Comment by MateusGuedess** [comment]
![captura de tela de 2018-08-17 15-37-21](https://user-images.githubusercontent.com/22087652/44283059-7aad2700-a233-11e8-837c-19caf42fdf48.png)

**Comment by talesbaz** [comment]
In fact the implementation via router class of EXPRESS is that needs this,
can be implemented (see [link](http://expressjs.com/pt-br/guide/routing.html)) in an alternative way. 
But I do not object to change, open the PR and mark the engineers team. Democracy rulez!

**Comment by VitorVRS** [comment]
According to the documentation you dont need to use Router() method.
Can you try to use examples in the link posted above?

**Comment by costamauricio** [comment]
Yep, we don't need to use Router(), we can achieve the same result using the express object, but we are using the routes as a module, a file per endpoint. We can't do that using express object.
