### ISSUE TITLE
Change PropTypes restriction

### ISSUE THREAD

**Issue by VitorVRS** [yaradigitallabs/eslint-config-yara#3]
Change `react/prop-types` from `error` to `warn`:
```
"react/prop-types": ["warn", {
  "ignore": [],
  "customValidators": [],
  "skipUndeclared": false
}]
```

**Comment by talesbaz** [comment]
Why ?

**Comment by VitorVRS** [comment]
I think this rule turns react development bureaucratic. There are some libs that do not offer proper support for this feature, forcing you to do some workaround to make it work, eg.: `PropTypes.instanceOf(Object)`

I had this conversation with @nathpaiva maybe she can give her opinion on this.

**Comment by talesbaz** [comment]
@nathpaiva can you give more detail to us, pls ?
